# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\x1a\x1bgoogle/protobuf/empty.proto\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\"8\n\x12\x43reateAdminRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\nMeResponse\x12\x10\n\x08username\x18\x01 \x01(\t2\xb0\x01\n\x0b\x41uthService\x12\x30\n\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\x12?\n\x0b\x43reateAdmin\x12\x18.auth.CreateAdminRequest\x1a\x16.google.protobuf.Empty\x12.\n\x02Me\x12\x16.google.protobuf.Empty\x1a\x10.auth.MeResponseB\x1cZ\x1awyron-panel/api/grpc/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032wyron-panel/api/grpc/proto'
  _globals['_LOGINREQUEST']._serialized_start=49
  _globals['_LOGINREQUEST']._serialized_end=99
  _globals['_LOGINRESPONSE']._serialized_start=101
  _globals['_LOGINRESPONSE']._serialized_end=131
  _globals['_CREATEADMINREQUEST']._serialized_start=133
  _globals['_CREATEADMINREQUEST']._serialized_end=189
  _globals['_MERESPONSE']._serialized_start=191
  _globals['_MERESPONSE']._serialized_end=221
  _globals['_AUTHSERVICE']._serialized_start=224
  _globals['_AUTHSERVICE']._serialized_end=400
# @@protoc_insertion_point(module_scope)
