# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x06server\x1a\x1bgoogle/protobuf/empty.proto\"\x91\x01\n\x06Server\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\x03\x12.\n\ninterfaces\x18\x06 \x03(\x0b\x32\x1a.server.WireGuardInterface\"\x9d\x01\n\x12WireGuardInterface\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x0e\n\x06subnet\x18\x03 \x01(\t\x12\x0b\n\x03\x64ns\x18\x04 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x05 \x01(\t\x12\x0c\n\x04port\x18\x06 \x01(\x05\x12\x12\n\npublic_key\x18\x07 \x01(\t\x12\x12\n\ncreated_at\x18\x08 \x01(\x03\"`\n\x13UpdateServerRequest\x12\x14\n\x0c\x64isplay_name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"6\n\x13ListServersResponse\x12\x1f\n\x07servers\x18\x01 \x03(\x0b\x32\x0e.server.Server\"\x1d\n\x0fServerIDRequest\x12\n\n\x02id\x18\x01 \x01(\t\"H\n\x17UpdateInterfaceResponse\x12-\n\tinterface\x18\x01 \x01(\x0b\x32\x1a.server.WireGuardInterface\"h\n\x10InterfaceRequest\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x04 \x01(\t\x12\x0b\n\x03\x64ns\x18\x05 \x01(\t2\x81\x03\n\rServerService\x12;\n\x04List\x12\x16.google.protobuf.Empty\x1a\x1b.server.ListServersResponse\x12.\n\x03Get\x12\x17.server.ServerIDRequest\x1a\x0e.server.Server\x12\x35\n\x06Update\x12\x1b.server.UpdateServerRequest\x1a\x0e.server.Server\x12\x39\n\x06\x44\x65lete\x12\x17.server.ServerIDRequest\x1a\x16.google.protobuf.Empty\x12L\n\x0fUpdateInterface\x12\x18.server.InterfaceRequest\x1a\x1f.server.UpdateInterfaceResponse\x12\x43\n\x0f\x44\x65leteInterface\x12\x18.server.InterfaceRequest\x1a\x16.google.protobuf.EmptyB\x1cZ\x1awyron-panel/api/grpc/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032wyron-panel/api/grpc/proto'
  _globals['_SERVER']._serialized_start=54
  _globals['_SERVER']._serialized_end=199
  _globals['_WIREGUARDINTERFACE']._serialized_start=202
  _globals['_WIREGUARDINTERFACE']._serialized_end=359
  _globals['_UPDATESERVERREQUEST']._serialized_start=361
  _globals['_UPDATESERVERREQUEST']._serialized_end=457
  _globals['_LISTSERVERSRESPONSE']._serialized_start=459
  _globals['_LISTSERVERSRESPONSE']._serialized_end=513
  _globals['_SERVERIDREQUEST']._serialized_start=515
  _globals['_SERVERIDREQUEST']._serialized_end=544
  _globals['_UPDATEINTERFACERESPONSE']._serialized_start=546
  _globals['_UPDATEINTERFACERESPONSE']._serialized_end=618
  _globals['_INTERFACEREQUEST']._serialized_start=620
  _globals['_INTERFACEREQUEST']._serialized_end=724
  _globals['_SERVERSERVICE']._serialized_start=727
  _globals['_SERVERSERVICE']._serialized_end=1112
# @@protoc_insertion_point(module_scope)
