// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserKey          string                 `protobuf:"bytes,1,opt,name=user_key,json=userKey,proto3" json:"user_key,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FirstConnectedAt int64                  `protobuf:"varint,3,opt,name=first_connected_at,json=firstConnectedAt,proto3" json:"first_connected_at,omitempty"`
	LastConnectedAt  int64                  `protobuf:"varint,4,opt,name=last_connected_at,json=lastConnectedAt,proto3" json:"last_connected_at,omitempty"`
	Usage            uint64                 `protobuf:"varint,5,opt,name=usage,proto3" json:"usage,omitempty"`
	TrafficLimit     uint64                 `protobuf:"varint,6,opt,name=traffic_limit,json=trafficLimit,proto3" json:"traffic_limit,omitempty"`
	DurationSeconds  int32                  `protobuf:"varint,7,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	SocialId         int64                  `protobuf:"varint,8,opt,name=social_id,json=socialId,proto3" json:"social_id,omitempty"`
	Active           bool                   `protobuf:"varint,9,opt,name=active,proto3" json:"active,omitempty"`
	Peers            []*Peer                `protobuf:"bytes,10,rep,name=peers,proto3" json:"peers,omitempty"`
	CreatedBy        string                 `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	SubToken         string                 `protobuf:"bytes,12,opt,name=sub_token,json=subToken,proto3" json:"sub_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *User) GetFirstConnectedAt() int64 {
	if x != nil {
		return x.FirstConnectedAt
	}
	return 0
}

func (x *User) GetLastConnectedAt() int64 {
	if x != nil {
		return x.LastConnectedAt
	}
	return 0
}

func (x *User) GetUsage() uint64 {
	if x != nil {
		return x.Usage
	}
	return 0
}

func (x *User) GetTrafficLimit() uint64 {
	if x != nil {
		return x.TrafficLimit
	}
	return 0
}

func (x *User) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *User) GetSocialId() int64 {
	if x != nil {
		return x.SocialId
	}
	return 0
}

func (x *User) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *User) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *User) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *User) GetSubToken() string {
	if x != nil {
		return x.SubToken
	}
	return ""
}

type Peer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerId       string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Interface      string                 `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	PrivateKey     string                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	AllowedAddress string                 `protobuf:"bytes,4,opt,name=allowed_address,json=allowedAddress,proto3" json:"allowed_address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *Peer) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Peer) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Peer) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *Peer) GetAllowedAddress() string {
	if x != nil {
		return x.AllowedAddress
	}
	return ""
}

type UserKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserKey       string                 `protobuf:"bytes,1,opt,name=user_key,json=userKey,proto3" json:"user_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserKeyRequest) Reset() {
	*x = UserKeyRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserKeyRequest) ProtoMessage() {}

func (x *UserKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserKeyRequest.ProtoReflect.Descriptor instead.
func (*UserKeyRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserKeyRequest) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

type AccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Interfaces    []string               `protobuf:"bytes,2,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRequest) Reset() {
	*x = AccessRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRequest) ProtoMessage() {}

func (x *AccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRequest.ProtoReflect.Descriptor instead.
func (*AccessRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *AccessRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *AccessRequest) GetInterfaces() []string {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type CreateUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserKey         string                 `protobuf:"bytes,1,opt,name=user_key,json=userKey,proto3" json:"user_key,omitempty"`
	TrafficLimit    uint64                 `protobuf:"varint,2,opt,name=traffic_limit,json=trafficLimit,proto3" json:"traffic_limit,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	SocialId        int64                  `protobuf:"varint,4,opt,name=social_id,json=socialId,proto3" json:"social_id,omitempty"`
	EndpointPort    int32                  `protobuf:"varint,5,opt,name=endpoint_port,json=endpointPort,proto3" json:"endpoint_port,omitempty"`
	ServerAccess    []*AccessRequest       `protobuf:"bytes,6,rep,name=server_access,json=serverAccess,proto3" json:"server_access,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserRequest) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

func (x *CreateUserRequest) GetTrafficLimit() uint64 {
	if x != nil {
		return x.TrafficLimit
	}
	return 0
}

func (x *CreateUserRequest) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *CreateUserRequest) GetSocialId() int64 {
	if x != nil {
		return x.SocialId
	}
	return 0
}

func (x *CreateUserRequest) GetEndpointPort() int32 {
	if x != nil {
		return x.EndpointPort
	}
	return 0
}

func (x *CreateUserRequest) GetServerAccess() []*AccessRequest {
	if x != nil {
		return x.ServerAccess
	}
	return nil
}

type EditUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserKey         string                 `protobuf:"bytes,1,opt,name=user_key,json=userKey,proto3" json:"user_key,omitempty"`
	TrafficLimit    *uint64                `protobuf:"varint,2,opt,name=traffic_limit,json=trafficLimit,proto3,oneof" json:"traffic_limit,omitempty"`
	DurationSeconds *int32                 `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3,oneof" json:"duration_seconds,omitempty"`
	SocialId        *int64                 `protobuf:"varint,4,opt,name=social_id,json=socialId,proto3,oneof" json:"social_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EditUserRequest) Reset() {
	*x = EditUserRequest{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditUserRequest) ProtoMessage() {}

func (x *EditUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditUserRequest.ProtoReflect.Descriptor instead.
func (*EditUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *EditUserRequest) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

func (x *EditUserRequest) GetTrafficLimit() uint64 {
	if x != nil && x.TrafficLimit != nil {
		return *x.TrafficLimit
	}
	return 0
}

func (x *EditUserRequest) GetDurationSeconds() int32 {
	if x != nil && x.DurationSeconds != nil {
		return *x.DurationSeconds
	}
	return 0
}

func (x *EditUserRequest) GetSocialId() int64 {
	if x != nil && x.SocialId != nil {
		return *x.SocialId
	}
	return 0
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SocialId      *int64                 `protobuf:"varint,1,opt,name=social_id,json=socialId,proto3,oneof" json:"social_id,omitempty"`
	Status        *string                `protobuf:"bytes,2,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Search        *string                `protobuf:"bytes,3,opt,name=search,proto3,oneof" json:"search,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip          int32                  `protobuf:"varint,5,opt,name=skip,proto3" json:"skip,omitempty"`
	Sort          string                 `protobuf:"bytes,6,opt,name=sort,proto3" json:"sort,omitempty"`
	Order         string                 `protobuf:"bytes,7,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *ListUsersRequest) GetSocialId() int64 {
	if x != nil && x.SocialId != nil {
		return *x.SocialId
	}
	return 0
}

func (x *ListUsersRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *ListUsersRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *ListUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUsersRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListUsersRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListUsersRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip          int64                  `protobuf:"varint,3,opt,name=skip,proto3" json:"skip,omitempty"`
	Users         []*User                `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *ListUsersResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListUsersResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUsersResponse) GetSkip() int64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type MetricsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalUsers        int64                  `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	ActiveUsers       int64                  `protobuf:"varint,2,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	DisabledUsers     int64                  `protobuf:"varint,3,opt,name=disabled_users,json=disabledUsers,proto3" json:"disabled_users,omitempty"`
	ExpiredUsers      int64                  `protobuf:"varint,4,opt,name=expired_users,json=expiredUsers,proto3" json:"expired_users,omitempty"`
	LimitedUsers      int64                  `protobuf:"varint,5,opt,name=limited_users,json=limitedUsers,proto3" json:"limited_users,omitempty"`
	TotalUsage        uint64                 `protobuf:"varint,6,opt,name=total_usage,json=totalUsage,proto3" json:"total_usage,omitempty"`
	TotalTrafficLimit uint64                 `protobuf:"varint,7,opt,name=total_traffic_limit,json=totalTrafficLimit,proto3" json:"total_traffic_limit,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *MetricsResponse) GetTotalUsers() int64 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *MetricsResponse) GetActiveUsers() int64 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

func (x *MetricsResponse) GetDisabledUsers() int64 {
	if x != nil {
		return x.DisabledUsers
	}
	return 0
}

func (x *MetricsResponse) GetExpiredUsers() int64 {
	if x != nil {
		return x.ExpiredUsers
	}
	return 0
}

func (x *MetricsResponse) GetLimitedUsers() int64 {
	if x != nil {
		return x.LimitedUsers
	}
	return 0
}

func (x *MetricsResponse) GetTotalUsage() uint64 {
	if x != nil {
		return x.TotalUsage
	}
	return 0
}

func (x *MetricsResponse) GetTotalTrafficLimit() uint64 {
	if x != nil {
		return x.TotalTrafficLimit
	}
	return 0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\x1a\x1bgoogle/protobuf/empty.proto\"\x93\x03\n" +
	"\x04User\x12\x19\n" +
	"\buser_key\x18\x01 \x01(\tR\auserKey\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12,\n" +
	"\x12first_connected_at\x18\x03 \x01(\x03R\x10firstConnectedAt\x12*\n" +
	"\x11last_connected_at\x18\x04 \x01(\x03R\x0flastConnectedAt\x12\x14\n" +
	"\x05usage\x18\x05 \x01(\x04R\x05usage\x12#\n" +
	"\rtraffic_limit\x18\x06 \x01(\x04R\ftrafficLimit\x12)\n" +
	"\x10duration_seconds\x18\a \x01(\x05R\x0fdurationSeconds\x12\x1b\n" +
	"\tsocial_id\x18\b \x01(\x03R\bsocialId\x12\x16\n" +
	"\x06active\x18\t \x01(\bR\x06active\x12 \n" +
	"\x05peers\x18\n" +
	" \x03(\v2\n" +
	".user.PeerR\x05peers\x12\x1d\n" +
	"\n" +
	"created_by\x18\v \x01(\tR\tcreatedBy\x12\x1b\n" +
	"\tsub_token\x18\f \x01(\tR\bsubToken\"\x8b\x01\n" +
	"\x04Peer\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1c\n" +
	"\tinterface\x18\x02 \x01(\tR\tinterface\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\tR\n" +
	"privateKey\x12'\n" +
	"\x0fallowed_address\x18\x04 \x01(\tR\x0eallowedAddress\"+\n" +
	"\x0eUserKeyRequest\x12\x19\n" +
	"\buser_key\x18\x01 \x01(\tR\auserKey\"L\n" +
	"\rAccessRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1e\n" +
	"\n" +
	"interfaces\x18\x02 \x03(\tR\n" +
	"interfaces\"\xfa\x01\n" +
	"\x11CreateUserRequest\x12\x19\n" +
	"\buser_key\x18\x01 \x01(\tR\auserKey\x12#\n" +
	"\rtraffic_limit\x18\x02 \x01(\x04R\ftrafficLimit\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x05R\x0fdurationSeconds\x12\x1b\n" +
	"\tsocial_id\x18\x04 \x01(\x03R\bsocialId\x12#\n" +
	"\rendpoint_port\x18\x05 \x01(\x05R\fendpointPort\x128\n" +
	"\rserver_access\x18\x06 \x03(\v2\x13.user.AccessRequestR\fserverAccess\"\xdd\x01\n" +
	"\x0fEditUserRequest\x12\x19\n" +
	"\buser_key\x18\x01 \x01(\tR\auserKey\x12(\n" +
	"\rtraffic_limit\x18\x02 \x01(\x04H\x00R\ftrafficLimit\x88\x01\x01\x12.\n" +
	"\x10duration_seconds\x18\x03 \x01(\x05H\x01R\x0fdurationSeconds\x88\x01\x01\x12 \n" +
	"\tsocial_id\x18\x04 \x01(\x03H\x02R\bsocialId\x88\x01\x01B\x10\n" +
	"\x0e_traffic_limitB\x13\n" +
	"\x11_duration_secondsB\f\n" +
	"\n" +
	"_social_id\"\xe6\x01\n" +
	"\x10ListUsersRequest\x12 \n" +
	"\tsocial_id\x18\x01 \x01(\x03H\x00R\bsocialId\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x02 \x01(\tH\x01R\x06status\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x03 \x01(\tH\x02R\x06search\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04skip\x18\x05 \x01(\x05R\x04skip\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\tR\x04sort\x12\x14\n" +
	"\x05order\x18\a \x01(\tR\x05orderB\f\n" +
	"\n" +
	"_social_idB\t\n" +
	"\a_statusB\t\n" +
	"\a_search\"u\n" +
	"\x11ListUsersResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04skip\x18\x03 \x01(\x03R\x04skip\x12 \n" +
	"\x05users\x18\x04 \x03(\v2\n" +
	".user.UserR\x05users\"\x97\x02\n" +
	"\x0fMetricsResponse\x12\x1f\n" +
	"\vtotal_users\x18\x01 \x01(\x03R\n" +
	"totalUsers\x12!\n" +
	"\factive_users\x18\x02 \x01(\x03R\vactiveUsers\x12%\n" +
	"\x0edisabled_users\x18\x03 \x01(\x03R\rdisabledUsers\x12#\n" +
	"\rexpired_users\x18\x04 \x01(\x03R\fexpiredUsers\x12#\n" +
	"\rlimited_users\x18\x05 \x01(\x03R\flimitedUsers\x12\x1f\n" +
	"\vtotal_usage\x18\x06 \x01(\x04R\n" +
	"totalUsage\x12.\n" +
	"\x13total_traffic_limit\x18\a \x01(\x04R\x11totalTrafficLimit2\x9c\x04\n" +
	"\vUserService\x12-\n" +
	"\x06Create\x12\x17.user.CreateUserRequest\x1a\n" +
	".user.User\x12'\n" +
	"\x03Get\x12\x14.user.UserKeyRequest\x1a\n" +
	".user.User\x12)\n" +
	"\x04Edit\x12\x15.user.EditUserRequest\x1a\n" +
	".user.User\x126\n" +
	"\x06Delete\x12\x14.user.UserKeyRequest\x1a\x16.google.protobuf.Empty\x126\n" +
	"\x06Enable\x12\x14.user.UserKeyRequest\x1a\x16.google.protobuf.Empty\x127\n" +
	"\aDisable\x12\x14.user.UserKeyRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\n" +
	"ResetUsage\x12\x14.user.UserKeyRequest\x1a\x16.google.protobuf.Empty\x127\n" +
	"\x04List\x12\x16.user.ListUsersRequest\x1a\x17.user.ListUsersResponse\x128\n" +
	"\aMetrics\x12\x16.google.protobuf.Empty\x1a\x15.user.MetricsResponse\x122\n" +
	"\x0eRevokeSubToken\x12\x14.user.UserKeyRequest\x1a\n" +
	".user.UserB\x1cZ\x1awyron-panel/api/grpc/protob\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_user_proto_goTypes = []any{
	(*User)(nil),              // 0: user.User
	(*Peer)(nil),              // 1: user.Peer
	(*UserKeyRequest)(nil),    // 2: user.UserKeyRequest
	(*AccessRequest)(nil),     // 3: user.AccessRequest
	(*CreateUserRequest)(nil), // 4: user.CreateUserRequest
	(*EditUserRequest)(nil),   // 5: user.EditUserRequest
	(*ListUsersRequest)(nil),  // 6: user.ListUsersRequest
	(*ListUsersResponse)(nil), // 7: user.ListUsersResponse
	(*MetricsResponse)(nil),   // 8: user.MetricsResponse
	(*emptypb.Empty)(nil),     // 9: google.protobuf.Empty
}
var file_user_proto_depIdxs = []int32{
	1,  // 0: user.User.peers:type_name -> user.Peer
	3,  // 1: user.CreateUserRequest.server_access:type_name -> user.AccessRequest
	0,  // 2: user.ListUsersResponse.users:type_name -> user.User
	4,  // 3: user.UserService.Create:input_type -> user.CreateUserRequest
	2,  // 4: user.UserService.Get:input_type -> user.UserKeyRequest
	5,  // 5: user.UserService.Edit:input_type -> user.EditUserRequest
	2,  // 6: user.UserService.Delete:input_type -> user.UserKeyRequest
	2,  // 7: user.UserService.Enable:input_type -> user.UserKeyRequest
	2,  // 8: user.UserService.Disable:input_type -> user.UserKeyRequest
	2,  // 9: user.UserService.ResetUsage:input_type -> user.UserKeyRequest
	6,  // 10: user.UserService.List:input_type -> user.ListUsersRequest
	9,  // 11: user.UserService.Metrics:input_type -> google.protobuf.Empty
	2,  // 12: user.UserService.RevokeSubToken:input_type -> user.UserKeyRequest
	0,  // 13: user.UserService.Create:output_type -> user.User
	0,  // 14: user.UserService.Get:output_type -> user.User
	0,  // 15: user.UserService.Edit:output_type -> user.User
	9,  // 16: user.UserService.Delete:output_type -> google.protobuf.Empty
	9,  // 17: user.UserService.Enable:output_type -> google.protobuf.Empty
	9,  // 18: user.UserService.Disable:output_type -> google.protobuf.Empty
	9,  // 19: user.UserService.ResetUsage:output_type -> google.protobuf.Empty
	7,  // 20: user.UserService.List:output_type -> user.ListUsersResponse
	8,  // 21: user.UserService.Metrics:output_type -> user.MetricsResponse
	0,  // 22: user.UserService.RevokeSubToken:output_type -> user.User
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_user_proto_msgTypes[5].OneofWrappers = []any{}
	file_user_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
